### ISSUE TITLE
`cursorActivity` event does not trigger angular change detection

### ISSUE THREAD

**Issue by urish** [TypeCtrl/ngx-codemirror#101]
Here is an example that reproduces this issue:

https://stackblitz.com/edit/code-mirror-issue?file=src%2Fapp%2Fapp.component.html

You will notice that if you move the cursor while the editor has focus, the coordinates of the cursor won't update until you blur the editor. A workaround I found was to manually trigger change detection, so it seems like wrapping the event listener with `NgZone.run()` can fix this.

If you wish, I can work on a PR for this. Thanks for creating this project!

**Comment by scttcper** [comment]
Hi Uri, I think I was looking at why so many change detection cycles were being triggered and turned a few things off. I've turned change detection back on for cursorActivity and left it off for scroll activity and added a note to the readme for that.

**Comment by urish** [comment]
Great, thanks for the super-quick response & fix!

p.s. I am using ngx-codemirror for [tsquery-playground](https://tsquery-playground.firebaseapp.com/), which visualizes the AST for given TypeScript code. Going to update it now with the new release :)
