### ISSUE TITLE
Try to use codemirror api, undefined method

### ISSUE THREAD

**Issue by calamarico** [TypeCtrl/ngx-codemirror#109]
I'm trying to call the ```autoFormatRange``` method editor instance, as [this](https://codemirror.net/2/demo/formatting.html) codemirror example does.

I'm using ViewChild to get the ngx-codemirror element, as this way:

```
export class ExampleComponent implements OnInit {
  @ViewChild('editor') editor:any;
  constructor(  ) { }

  ngOnInit() {
    console.log(this.editor);
    this.editor.autoFormatRange(0,1);
  }
}
```
Editor is an object, a CodemirrorComponent, the autoFormat call obviously don't work because autoFormatRange is undefined, is there any way to use the codemirror api?

Thanks!

**Comment by tmirun** [comment]
Hey @calamarico, i think you can use this.editor.codeMirror instance of this.editor
