### ISSUE TITLE
Lint errors not showing

### ISSUE THREAD

**Issue by sammaphey** [TypeCtrl/ngx-codemirror#147]
I have tried adding lint errors to the codemirror instance but they do not show up. 

app.module.ts: 
```
import { CodemirrorModule } from '@ctrl/ngx-codemirror';
import 'codemirror/mode/javascript/javascript';
import 'codemirror/addon/lint/lint';
```

codeMirrorOptions: 
```
  codeMirrorOptions = {
    lineNumbers: true,
    theme: 'material',
    lint: true,
    gutters: ['CodeMirror-lint-markers'],
    mode: {
      name: 'javascript', json: true
    }
  };
```

It seems like this is all that is needed. Am I missing something?

Thanks

**Comment by scttcper** [comment]
I think you need to include the linter for json as well

**Comment by Lertis** [comment]
@scttcper Where I can see any examples?
