### ISSUE TITLE
Placeholder in editor

### ISSUE THREAD

**Issue by rostik-t** [TypeCtrl/ngx-codemirror#162]
Hi!
It would be great to add some custom placeholder if the code area is empty.
There is a placeholder addon in CodeMirror (https://codemirror.net/demo/placeholder.html), but it requires the textarea component to have this property, which is impossible to set in ngx-codemirror

**Comment by tothandras** [comment]
Hi, it seems to be working:

```ts
// see https://codemirror.net/demo/placeholder.html
import 'codemirror/addon/display/placeholder';
```

```html
<ngx-codemirror [options]="{ placeholder: 'text' }"></ngx-codemirror>
```

**Comment by rostik-t** [comment]
Wow! Thanks, really working.
There was no mentioning that this parameter can be placed in options
