### ISSUE TITLE
question: how to set height

### ISSUE THREAD

**Issue by quartelh** [TypeCtrl/ngx-codemirror#186]
Hi,

I am trying to include ngx-codemirror into my angular app, but I am struggling to (dynamically) set the height of the editor.

I looked at the CodeMirror docs, but did not manage to figure it out in combination with ngx-codemirror.

How did you solve this?

**Comment by phillsonntag** [comment]
You can set the height global in your project, just add the CodeMirror class to your styles.css. 

Example: 
`.CodeMirror {
  height: fit-content!important;
}`

I also couldn't find a way to set the height of a single editor.

**Comment by scttcper** [comment]
use a css class

**Comment by elcsiga** [comment]
@Component({
        template: '<ngx-codemirror></ngx-codemirror>'
    })
    export class MyCodeMirrorWrapperComponent implements OnInit{
        constructor(
            private elementRef: ElementRef,
        ) {}
        ngOnInit() {
            setTimeout(() => {
                try {
                    this.elementRef.nativeElement
                        .getElementsByClassName('CodeMirror').item(0)
                        .setAttribute('style', 'height: auto;'); // set the appropriate height here - 'auto' will fit the content
                } catch (e) {} // eslint-disable-line no-empty
            }, 0);
        }
