### ISSUE TITLE
[Suggestion] Add an EditorCreated Output

### ISSUE THREAD

**Issue by marlon-tucker** [TypeCtrl/ngx-codemirror#191]
Hello,

I have a requirement that I need to set some syntax highlighting via the use of CM's "Text Marking" capabilities, at the moment the editor instance is inside the component without a way to get at it. The cursor activity event emits it as its output but for my requirement I need access to it before the user interacts with the text.

Any chance the editor instance can be exposed pleased?

**Comment by scttcper** [comment]
the editor instance is exposed https://github.com/TypeCtrl/ngx-codemirror/blob/389e18e6603dd06f909ce019521a5f13348b7f5f/src/lib/codemirror.component.ts#L90

Use a viewchild to select ngx-codemirror and then use the instance directly

**Comment by marlon-tucker** [comment]
Ah ok, I forgot the viewchild was an option. 

Closing
