### ISSUE TITLE
How can I refresh the codemirror?

### ISSUE THREAD

**Issue by SaulFein** [TypeCtrl/ngx-codemirror#192]
I am having an issue were the user input is over lapping the line numbers and I have read that using the codemirror refresh button might help fix the issue. This issue only happens in the code mirror instance my modal. How do I access the codemirror function from this angular version?

![image](https://user-images.githubusercontent.com/12875543/61970374-818b0080-af91-11e9-86db-23d1e7b9e7f4.png)

Thanks

**Comment by scttcper** [comment]
access the codemirror instance
https://github.com/TypeCtrl/ngx-codemirror/issues/191#issuecomment-508228492

**Comment by SaulFein** [comment]
Okay thank you this helped me get access to the CodeMirror instance. I am searching through the CodeMirror component and I am not finding a method that has refresh() method on it. In the intellisense for the EditorFromTextArea class the refresh() method is there but when the code loads it comes up as a CodemirrorComponent in the browser's debugger. Is there a method in there that will refresh the text editor? Thanks for your help.

**Comment by scttcper** [comment]
yeah the "codemirror" EditorFromTextArea is going to be the codemirror instance and you'll need to do it with that. I'm not sure what the function would be.

**Comment by SaulFein** [comment]
Thanks for your help. I tried to refresh using the codemirror instance but could not find the right method. I was able to resolve this by using a *ngIf with boolean flag and setting that flag from flag to true in a setTimeout on ngInit. That allowed the code mirror editor to render properly in my modal

**Comment by rochapablo** [comment]
Thanks to @SaulFein`*ngIf` did the trick. Using Dialog:

```
<div *ngIf="ready"><ngx-codemirror [options]="{ lineNumbers: true, mode: 'markdown' }"></ngx-codemirror></div>
```

```
this.dialogRef.afterOpened().subscribe(() => setTimeout(() => this.ready = true, 0));
```
