### ISSUE TITLE
Edit json object issue

### ISSUE THREAD

**Issue by arnevdv** [TypeCtrl/ngx-codemirror#207]
Is there a way to edit a full json object (with typing) in the code mirror?
When I try to pass a json object I get following error:

`
ERROR Error: Uncaught (in promise): TypeError: str.replace is not a function
TypeError: str.replace is not a function
`

Any ideas?

**Comment by scttcper** [comment]
The demo has a json editing example, maybe start there

**Comment by arnevdv** [comment]
@scttcper Does not work at all. Has no decent json layout. All data displays on a single line...

**Comment by scttcper** [comment]
You have to stringify the json into multiple lines. Use the 3rd parameter to json.stringify
