### ISSUE TITLE
change height and width of codemirror in angular

### ISSUE THREAD

**Issue by helxsz** [TypeCtrl/ngx-codemirror#213]
i am using angular 7 with latest ngx-codemirror.

    <ngx-codemirror [(ngModel)]="sql_input"  [options]="{lineNumbers: true,theme: 'material',mode: 'markdown'}"></ngx-codemirror>

The final looks is shown as below, which is too big size for me. Just wonder how to resize it to be more smaller in height and width.

![Screen Shot 2019-10-19 at 02 33 10](https://user-images.githubusercontent.com/669670/67136075-478c6c00-f219-11e9-824c-c9935c1daf17.png)

**Comment by scttcper** [comment]
it takes the size of the parent element
