### ISSUE TITLE
[Highlight] Highlighting row only in view

### ISSUE THREAD

**Issue by vmagalhaes** [TypeCtrl/ngx-codemirror#224]
Hi,

I have a problem with the row highlight. I'm trying to use SHIFT + KEYS, to highlight the row and do some tests, but the codemirror are highlighting only the view of the row, I needed to highlight all the row, with whitespace and any characters that are on the row.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/14242447/69443137-96538700-0d2c-11ea-91b2-2ca0c2b1596e.gif)

What can I do?

Regards,
Victor Magalhães.

**Comment by scttcper** [comment]
I'm not sure how ngx-codemirror would've caused this. I see you've opened https://github.com/codemirror/CodeMirror/issues/6074 already. I'll leave this open though

**Comment by vmagalhaes** [comment]
Ok! Thanks Scoot

**Comment by vmagalhaes** [comment]
Scott!
