### ISSUE TITLE
Column number masking code

### ISSUE THREAD

**Issue by waker744524423** [TypeCtrl/ngx-codemirror#225]
Hello, when I use ngx-mirror, the serial number is blocked. I think there is a problem with the writeValue logic. But I don't know how to solve it. I hope you can help.
![image](https://user-images.githubusercontent.com/26833271/69705150-eb7a0900-112f-11ea-9bed-535bc385ba0d.png)
thanks！

**Comment by scttcper** [comment]
looks like a css issue

**Comment by waker744524423** [comment]
Thanks Reply.Yes, after this.codeMirror.setValue (this.value) ;, the css is not finished yet. The cursor is also problematic. I am a newcomer, and I can only see this degree. Hahaha

**Comment by scttcper** [comment]
Okay since codemirror is rendering I’m going to go ahead and close, this library really doesn’t do anything
