### ISSUE TITLE
Ivy: compilation fails

### ISSUE THREAD

**Issue by smnbbrv** [TypeCtrl/ngx-codemirror#226]
Hi,

just tried to switch my project to use Ivy and got an error

> Compiling @ctrl/ngx-codemirror : es2015 as esm2015
> 
> ERROR in No suitable injection token for parameter '_differs' of class 'CodemirrorComponent'.
> no type or decorator

If I just copy the component locally, it works just fine. So, something should be adapted in the build process I guess

**Comment by scttcper** [comment]
should be working w/ latest version and 9

**Comment by smnbbrv** [comment]
Yes it does. Thanks
