### ISSUE TITLE
How do I enable hinting + Javascript hinting?

### ISSUE THREAD

**Issue by andrewryan1906** [TypeCtrl/ngx-codemirror#235]
I am trying to make it so that when you select Ctrl-Space the system shows you Javascript hints, like in this example:

https://codemirror.net/demo/complete.html

I think I'm missing something here; not sure how to make this work. In my config:

```
{

    theme: 'blackboard',
    lineNumbers: true,
    smartIndent: true,
    extraKeys: {'Ctrl-Space': 'autocomplete'}
  };
```

In main.ts:

```
import "codemirror/addon/hint/show-hint";
import "codemirror/addon/hint/javascript-hint";
import "codemirror/addon/hint/css-hint";
import "codemirror/addon/hint/html-hint";
```

And in angular.json:

```
     "styles": [
...
              "node_modules/codemirror/addon/hint/show-hint.css",

            ],
```

I'm expecting the javascript hinting to function as it does in the example; when I move the cursor to line 3 and type "fou" and hit Ctrl-Space, the editor autocompletes to the variable "found".

Doesn't work.

What am I missing?

**Comment by esteban-gs** [comment]
I'm also hoping to use the show hint option.

**Comment by assimbly** [comment]
Should this be working right now? Is there a working example of it? Or isn't this implemented yet?
