### ISSUE TITLE
Java mode

### ISSUE THREAD

**Issue by Suranchiyev** [TypeCtrl/ngx-codemirror#243]
I couldn't set up Java by using this library. Does it support Java?

**Comment by geisterfurz007** [comment]
You should use the mode `text/x-java` for codemirror (see [the list of out-of-the-box-supported modes](https://codemirror.net/mode/index.html)), especially Java, which links to [clike](https://codemirror.net/mode/clike/index.html) which then lists the defined mimetypes in the bottom with `text/x-java` listed for Java.
