### ISSUE TITLE
pass the json values to the codemirror

### ISSUE THREAD

**Issue by helxsz** [TypeCtrl/ngx-codemirror#271]
in the my app

html as show
` <ngx-codemirror [(ngModel)]="data" [autoFocus]=true [options]="{lineNumbers: true,theme: 'material',mode: 'markdown'}"></ngx-codemirror>`

ts as show 
```
   data='';
   json = {
        "title": "Type",
        "description": "A type of product",
        "type": "object"
  };

constructor(){
      this.data = JSON.stringify(this.json);
}
```
it shows correctly the json text in a single line, but I want to show it in a json format instead of a string within a single line.

how would I do that?

**Comment by neil-coutinho** [comment]
@helxsz Did you manage to resolve you're JSON as a single line issue?

**Comment by scttcper** [comment]
json.stringify formats into one line, but there's a third argument `JSON.stringify(data, null, 2)`
