### ISSUE TITLE
Typing becomes laggy

### ISSUE THREAD

**Issue by MikeWoots** [TypeCtrl/ngx-codemirror#63]
Hi

I have been experiencing an issue where typing in the editor is fine to start with but as more text is added or removed then typing or changing the text in the editor becomes very laggy. I have a two way binding with NgModel to update the text variable.

```
    "@ctrl/ngx-codemirror": "^1.3.4",
```
Also using angular 5. 

Could you let me know if you have any suggestions on how I could improve performance.

**Comment by scttcper** [comment]
How much text in the editor? Can you reproduce it on the demo?

**Comment by MikeWoots** [comment]
After adding and deleting maybe 20/30 lines a couple of times, it becomes noticeable. I wasn't able to replicate it using the demo. If I load text in programmatically rather than actually typing, I find it also effects the performance more.

```
      <ngx-codemirror
        [(ngModel)]="text"
        (ngModelChange)='changed($event)'
        [options]="{lineNumbers: false, theme: 'eclipse', mode: 'text/x-sql'}"
        [autoFocus]="true">
      </ngx-codemirror>
```
```
  public text: string;

  constructor( ) {
    this.modelChanged
      .debounceTime(1500) // wait 1500ms after the last event before emitting last event
      .distinctUntilChanged() // only emit if value is different from previous value
      .subscribe(model => {
        delete this.text;
        this.text = model;
      });
  }

  changed(text: string) {
    this.modelChanged.next(text);
  }
```

I tried to add a debounce on the ngModel change but that didn't seem to improve it.

**Comment by scttcper** [comment]
try making it `[ngModel]` without 2 way binding. Also try removing the `(ngModelChange)` to make sure that isn't whats slow.
