### ISSUE TITLE
Addons?

### ISSUE THREAD

**Issue by patricknee** [TypeCtrl/ngx-codemirror#90]
Any guidance about how to use Codemirror addons?

**Comment by scttcper** [comment]
Import the addons like you do the langauge files https://github.com/TypeCtrl/ngx-codemirror#use

**Comment by patricknee** [comment]
I resolved this. For others, it involved (for a Angular cli 6 project):

Adding to index.html:

`<script src="//ajax.aspnetcdn.com/ajax/jshint/r07/jshint.js"></script>`

Adding to styles.css:

`@import "~codemirror/addon/lint/lint.css";`

Adding to the component holding the edit panel:

```
import 'codemirror/addon/lint/lint';
import 'codemirror/addon/lint/javascript-lint';
```
The resulting HTML element:

```
      <ngx-codemirror [(ngModel)]="content"
        [options]="{
        lineNumbers: true,
        theme: 'material',
        mode: 'javascript',
        gutters: ['CodeMirror-lint-markers'],
        lint: true
        }"
      ></ngx-codemirror>
```
